### PR TITLE
Add unit tests for com.mm.dao and com.mm.model 

### PR DESCRIPTION
**Pull request by paulkennethkent**
I've analysed your codebase and noticed that `com.mm.dao` and `com.mm.model` have not been tested.

These tests have been created by [Diffblue Cover](https://www.diffblue.com/opensource) and filtered for their quality via our test ranking system. We like to hear your feedback on the quality of these tests and whether you would consider them as mergeable. 

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important in a subsequent PR.

### CODE REVIEW

**Review by JohnLBergqvist — COMMENTED** [review]
Looks fine but you're still keeping the timeout & our comments in?

**Comment by Braavos6** [comment]
Shouldn't the commit message have the `package Name.class` ?

**Comment by paulkennethkent** [comment]
> Shouldn't the commit message have the `package Name.class` ?

There are 6 classes, a commit for every class? @Braavos96

**Comment by Braavos6** [comment]
> > Shouldn't the commit message have the `package Name.class` ?
> 
> There are 6 classes, a commit for every class? @Braavos96

Yeah... maybe just package name? otherwise its fine

**Pull request closed without merging**
